### ISSUE TITLE
Crashes with Genisys

### ISSUE THREAD

**Issue by TheGalaxyLord** [PocketKiller/ShootingRod#3]
Title says it and there is the crash dump

Genisys Crash Dump Fri Feb 26 16:12:20 ACT 2016

Error: syntax error, unexpected ';'
File: /plugins/ShootingRod-master/src/PocketKiller/ShootingRod/Main
Line: 133
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN
此次出错由插件引起

Code:
[124] 		return true;
[125] 	}
[126] 
[127] 	private function removeUser(Player $p) : bool{
[128] 		unset($this->users[array_search($p->getId(), $this->users)]);
[129] 		return true;
[130] 	}
[131] 
[132] 	public function setAllowed(Player $p, bool $b) : bool{
[133] 		!($b) ? $this->disallowed[$p->getId()] = $p->getId(); : unset($this->disallowed[$p->getId()]);
[134] 		return true;
[135] 	}
[136] 
[137] 	public function isAllowed(Player $p) : bool{
[138] 		return isset($this->disallowed[$p->getId()]);
[139] 	}
[140] }
[141] 
[142] 
[143] 

Backtrace:
#0 (): spl_autoload_call(string PocketKiller\ShootingRod\Main)
#1 /src/pocketmine/plugin/FolderPluginLoader(48): class_exists(string PocketKiller\ShootingRod\Main, boolean 1)
#2 /src/pocketmine/plugin/PluginManager(155): pocketmine\plugin\FolderPluginLoader->loadPlugin(string C:\Users\Michael\Desktop\PocketVenom\plugins\ShootingRod-master)
#3 /src/pocketmine/plugin/PluginManager(301): pocketmine\plugin\PluginManager->loadPlugin(string C:\Users\Michael\Desktop\PocketVenom\plugins\ShootingRod-master, array Array())
#4 /src/pocketmine/Server(1934): pocketmine\plugin\PluginManager->loadPlugins(string C:\Users\Michael\Desktop\PocketVenom\plugins\)
#5 /src/pocketmine/PocketMine(465): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Michael\Desktop\PocketVenom\, string C:\Users\Michael\Desktop\PocketVenom\, string C:\Users\Michael\Desktop\PocketVenom\plugins\)

Genisys version: 1.1dev #0 [Protocol 45; API 2.0.0]
uname -a: Windows NT MICHAEL 10.0 build 10586 (Windows 10) i586
PHP version: 7.0.1
Zend version: 3.0.0
OS : WINNT, win

Loaded plugins:
加载的插件:
1vs1 0.0.5 by  for API(s) 1.0.0, 1.1.0
AdvancedKits 4.0.1 by luca28pet for API(s) 1.12.0
Alias 1.2.0 by ZacHack for API(s) 1.12.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
AntiLagg 1 by Mrswa9 for API(s) 1.13.0
BasicHUD 1.0.6 by aliuly for API(s) 1.12.0
BuyCraft 1.2.2 by Falkirks for API(s) 1.0.0
Cameraman 1.1 by ChalkPE for API(s) 1.12.0, 1.13.0, 2.0.0
mcg76_CTF 1.6.0 by minecraftgenius76, MCG76 for API(s) 1.12.0
CombatLogger 1.2.0 by Lambo for API(s) 1.12.0
CommandDefender 1.0-Alpha by ifteam for API(s) 1.12.0, 1.13.0, 2.0.0
CommandTracker 1.1 by Scott Handley for API(s) 1.10.0
CrateKeys 1.0.5 by CDFalcon, CDFalcon for API(s) 1.13.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
DN 0.1 by Taki21 for API(s) 1.13.2
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
EnderPearl 1.2.3 by Yosshi999 for API(s) 1.0.0, 1.1.0
FloatingTexter 1.0 by Heromine/Jon for API(s) 1.12.0
GravityHammer 1.0.0 by DA_SWAGNEMITE for API(s) 1.10.0
HealthTag 1 by iDirtPlaysMC-EnderKenji for API(s) 1.3.1
HideTag 1 by Wantedkillers (Author), SenorContento (Editor) for API(s) 1.10.0
iProtector 3.1a by LDX for API(s) 1.9.0
ItemEffects 2.5.0 by XFuryMCPE for API(s) 1.12.0
Launchpads 1.0.0 by BukkitPlaysMC for API(s) 1.0.0
Lightning_Strike 2 by MichaelM04 for API(s) 1.0.0
ManyWorlds 2.0.3 by aliuly for API(s) 2.0.0, 1.13.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
MSpleef 3.5 Beta by MCrafters for API(s) 1.12.0
MultiInventory 1 by luca28pet for API(s) 1.12.0
NetherChests 1.1.1 by aliuly for API(s) 1.12.0
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
Op-Manger 3.0.1 by MCrafters for API(s) 1.0.0
PlanB 1.3.0 by Gamecrafter for API(s) 1.10.0
PopupAlerts 1.3 by EvolSoft for API(s) 1.12.0
PurePerms 1.3.0 by 64FF00 for API(s) 1.13.0, 2.0.0
ReportPE 1.0.0 by applqpak for API(s) 1.0.0
RestartMe 1.2.0 by Gamecrafter for API(s) 1.10.0
ServerChannels 1.2 by EvolSoft for API(s) 1.11.0
ServerLoveMCPE 3.2 by TheDeibo, ratchetgame98, and, The Plugin Community! for API(s) 1.10.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
Slapper 1.2.9.3_PHP7 by jojoe77777 for API(s) 1.12.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
TheDropper 1.0.0 by  for API(s) 1.1.0
TimeCapsule 1.1.1 by Falk for API(s) 1.0.0
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
TNTRun 1.0.0 by BukkitPlaysMC for API(s) 1.0.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
VPNGuard 1.0.4 by basprohop for API(s) 1.10.0
WarnPlayer 1.0.0 by applqpak for API(s) 1.0.0
WorldFixer 1 by CreeperFace for API(s) 1.12.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
xyz 1.0.1 by unerds for API(s) 1.0.0
YouChat 1.0.1 by aliuly for API(s) 1.12.0
MTeamPvP 1.0.0 Beta by MCrafters for API(s) 1.12.0

**Comment by XShockinFireX** [comment]
i get the same error.

**Comment by PocketKiller** [comment]
sorry!
